apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.kubernetes.app }}-external-secret
  namespace: {{ .Values.kubernetes.namespace }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: {{ .Values.kubernetes.app }}-secret-store
  target:
    name: {{ .Values.kubernetes.app }}-secret
    creationPolicy: Owner
  # Secret Manager 에서 Value 가 JSON 포맷으로 선언되어 있어야 함
  dataFrom:
  - extract:
      # Secret Manager 이름
      key: {{ .Values.kubernetes.app }}-{{ .Values.deployment }}
      version: {{ .Values.gcp.secretManager.version }}
