apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.kubernetes.app }}-secret-store
  namespace: {{ .Values.kubernetes.namespace }}
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.gcp.project.id }}
      auth:
        workloadIdentity:
          clusterLocation: {{ .Values.gcp.cluster.zone }}
          clusterName: {{ .Values.gcp.cluster.name }}
          clusterProjectID: {{ .Values.gcp.project.id }}
          serviceAccountRef:
            name: {{ .Values.kubernetes.app }}
