apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kubernetes.app }}
  namespace: {{ .Values.kubernetes.namespace }}
  labels:
    app: {{ .Values.kubernetes.app }}
  annotations:
    cloud.google.com/backend-config: |
      {"ports": {"80":"{{ .Values.kubernetes.app }}-backendconfig"}}
    cloud.google.com/neg: '{"ingress": true}'

spec:
  type: ClusterIP
  selector:
    app: {{ .Values.kubernetes.app }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}

